version: '2'

services:
  fpm:
    image: php:7.1-fpm-jessie
    env_file: ['.env']
    volumes:
      - "./:/app/"

  nginx:
    image: nginx:1.13.6
    volumes:
      - "./web:/app/web"
      - ./docker/prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - "8080:80"

  redis:
    image: redis:3.2


