imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    cache:
      app: cache.adapter.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false
